no_of_threads=4

// thread=cpu_no
thread_1=4
thread_2=5
thread_3=6
thread_4=7


// thread= task ( logging, upstream, downstream, etc)
thread_task_1=logging
thread_task_2=upstream
thread_task_3=downstream
thread_task_4=

//upstream connection
upstream_connection_type=webSocket
upstream_connection_no=1
upstream_connection_1=wss://fstream.binance.com/public
upstream_connection_port_1=443

//downstream connection
// TODO